### ISSUE TITLE
ORB_SLAM2 or ORB_SLAM3

### ISSUE THREAD

**Issue by yanqswhu** [zhaozhongch/infinitam_ros#1]
ORB_SLAM2 is more robust than ORB_SLAM3 in rgbd. 
https://github.com/UZ-SLAMLab/ORB_SLAM3/issues/8

So it will be a good choice to use ORB_SLAM2.

**Comment by zhaozhongch** [comment]
I can run ORBSLAM3 rgbd without a problem. But anyway, that is just an example showing you can apply an external tracker to the infinitam. You can use whatever tracker you want as long as it can publish the pose topic.
